# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

networks:
  ssl-reverse-proxy:
    external: yes

services:
  ssl-reverse-proxy:
    image: "abiosoft/caddy:${CADDY_TAG:-latest}"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - ssl-reverse-proxy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ${HOME}/.caddy:/root/.caddy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
