# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

version: "3"

networks:
  ssl-reverse-proxy:
    external: yes

services:
  ssl-reverse-proxy:
    build:
      context: .
      args:
        CADDY_TAG: ${CADDY_TAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - ssl-reverse-proxy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
        # Uncomment only after:
        #   $ mkdir -m 0700 caddy-home
        #   $ sudo chown 65534:65534 caddy-home
      # - ./caddy-home:/home/caddy/
    user: '65534:65534'
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
