# Copyright (c) 2024 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

name: Run smoke test

# Drop permissions to minimum for security
permissions:
  contents: read

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

jobs:
  smoke_test:
    name: Run the test suite
    strategy:
      matrix:
        python-version: ["3.10", 3.14]  # no particular need for in-between versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run smoke test
      run: |
        set -x
        python3 --version
        ./Caddyfile.generate --config sites.cfg.EXAMPLE --saltstack > actual-output.txt
        diff -u0 \
            <(tail -n +3 .github/workflows/expected-output.txt) \
            <(tail -n +3 actual-output.txt)
